# Generated by Django 3.2.25 on 2024-03-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalprofile.plan'),
        ),
    ]
