# Generated by Django 3.2.25 on 2024-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0003_personalinformation_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='year_of_birth',
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='marital_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='residency_status',
            field=models.CharField(max_length=200),
        ),
    ]
