# Generated by Django 3.2.25 on 2024-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0005_userpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='age',
            new_name='age_max',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
