# Generated by Django 3.2.25 on 2024-03-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0008_auto_20240318_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='user',
            new_name='user_id',
        ),
    ]
