# Generated by Django 3.2.25 on 2024-03-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0009_rename_user_personalinformation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='user_id',
            new_name='user',
        ),
    ]
