# Generated by Django 3.2.25 on 2024-03-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0010_rename_user_id_personalinformation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='drinking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
