# Generated by Django 3.2.25 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0011_auto_20240319_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
