# Generated by Django 3.2.25 on 2024-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalprofile', '0014_alter_imageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.CharField(default=0, max_length=20000),
        ),
    ]
