swagger: '2.0'
info:
  version: '1.0.0'
  title: 'My API'
  description: 'This is my API.'
paths:
  /users:
    get:
      summary: 'Get all users.'
      responses:
        '200':
          description: 'A list of users.'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/User'
  /users/{id}:
    get:
      summary: 'Get a user by ID.'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          type: 'integer'
      responses:
        '200':
          description: 'A user.'
          schema:
            $ref: '#/definitions/User'
definitions:
  User:
    type: 'object'
    properties:
      id:
        type: 'integer'
      name:
        type: 'string'
